#!/usr/bin/env bash

# bash_exports

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Make vim the default editor
export EDITOR='/usr/local/bin/vim'
export BUNDLER_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR

# Github ruby config
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1.25
export RUBY_HEAP_MIN_SLOTS=800000
export RUBY_FREE_MIN=600000

# Maven
export MAVEN_OPTS="-Xms750m -Xmx2100m -XX:MaxPermSize=384m -XX:+UseCompressedOops"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Export PhantomJS bin location (be explicit in case Homebrew is not installed
# in the default location)
# export PHANTOMJS_BIN="$(brew --prefix)/bin/phantomjs"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
