set linespace=2
set antialias "MacVim: smooth fonts."
set encoding=utf-8
set guifont=Source\ Code\ Pro:h18
color monokai

" Don't beep
set visualbell

set guioptions-=T   " No toolbar
set guioptions-=r   " No scrollbars
set guioptions-=L

if has("gui_macvim")
  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert
end
